//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotExpander {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LEStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LEStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotExpander.LEStrings", typeof(LEStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lot adjustment was aborted!.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced....
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lot may have been corrupted.
        ///
        ///DO NOT SHARE this lot.  EVER!
        ///	.
        /// </summary>
        internal static string Corrupted {
            get {
                return ResourceManager.GetString("Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount to enlarge the lot, viewed from the front.
        ///	.
        /// </summary>
        internal static string EnlargeExpl {
            get {
                return ResourceManager.GetString("EnlargeExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lot was changed!.
        /// </summary>
        internal static string Erfolg {
            get {
                return ResourceManager.GetString("Erfolg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lot adjustment was aborted! An error occurred during modification of your lot. The current version of the LotAdjuster is unable to continue.
        ///
        ///Please report this error at: http://www.modthesims.info/showthread.php?t=384656 and attach a copy of your lot to the posting.
        ///	.
        /// </summary>
        internal static string ExplainAbort {
            get {
                return ResourceManager.GetString("ExplainAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Lot is empty and cannot be adjusted.
        ///
        ///Run the game and make a build change, then save the lot.  Rerun the LotAdjuster.
        ///	.
        /// </summary>
        internal static string ExplainEmptyLotAbort {
            get {
                return ResourceManager.GetString("ExplainEmptyLotAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}:
        ///{1} is in an invalid location
        ///
        ///Remove everything from the area to be trimmed, plus one additional tile at the edge of the new lot.  Then rerun the LotAdjuster.
        ///	.
        /// </summary>
        internal static string ExplainShrinkAbort {
            get {
                return ResourceManager.GetString("ExplainShrinkAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You have chosen not to continue with the lot adjustment.
        ///	.
        /// </summary>
        internal static string ExplainUserAbort {
            get {
                return ResourceManager.GetString("ExplainUserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lot was changed.  Complete the following steps to finish the process:
        ///
        ///1) Start the game and load the neighbourhood. The lot may appear to be empty.
        ///
        ///2) Load the lot and make at least one structural change. Save and return to the neighbourhood.
        ///
        ///3) DON&apos;T move the lot in the neighborhood!  If you do, the roads will be rebuilt.
        ///
        ///The lot adjustment is complete and your modified lot is available for use..
        /// </summary>
        internal static string FinalExplNoMove {
            get {
                return ResourceManager.GetString("FinalExplNoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LotAdjuster has completed the modification of your lot.  Complete the following steps to finish the process:
        ///
        ///1) Start the game and load the neighbourhood.
        ///
        ///2) To fix the view of the lot in the neighborhood, load the lot and make at least one structural change. Save and return to the neighbourhood.
        ///
        ///The lot adjustment is complete and your modified lot is available for use.
        ///	.
        /// </summary>
        internal static string FinalExplUnlock {
            get {
                return ResourceManager.GetString("FinalExplUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lot was changed.  Complete the following steps to finish the process:
        ///
        ///1) Start the game and load the neighbourhood. The lot may appear to be empty.
        ///
        ///2) Load the lot and make at least one structural change. Save and return to the neighbourhood.
        ///
        ///3) To regenerate the road, pick up the lot in the neighborhood view and move it until it &quot;snaps&quot; to the road.
        ///
        ///4) You may need to edit the lot one more time: to delete excess road tiles and sidewalks, and to move the mailbox and garbage can.
        ///
        ///The lot a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinalExplWithMove {
            get {
                return ResourceManager.GetString("FinalExplWithMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Lot:.
        /// </summary>
        internal static string LotTitle {
            get {
                return ResourceManager.GetString("LotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, the LotAdjuster may corrupt your neighborhood or lot.
        ///Do not continue unless you have a current backup.
        ///
        ///Do you really want to continue?
        ///	.
        /// </summary>
        internal static string MessageCorruptLot {
            get {
                return ResourceManager.GetString("MessageCorruptLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unfinished Feature.
        ///You can use it to enlarge your lot on the other side of the street.
        ///After using this, don&apos;t replace the lot anymore. So you can&apos;t share it.
        ///Do you want to use this feature?.
        /// </summary>
        internal static string MessageKeepStreet {
            get {
                return ResourceManager.GetString("MessageKeepStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unfinished Feature.
        ///You can use it to move your lot in the neighborhood.
        ///After using this, don&apos;t replace the lot anymore. So you can&apos;t share it.
        ///Do you want to use this feature?.
        /// </summary>
        internal static string MessageMoveLot {
            get {
                return ResourceManager.GetString("MessageMoveLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t change any of this Lot&apos;s Values.
        ///So the only effect is unlocking all tiles of the lot.
        ///Tiles will only remain unlocked until you replace the lot the next time.
        ///Is this your intention?.
        /// </summary>
        internal static string MessageNoChange {
            get {
                return ResourceManager.GetString("MessageNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot modify this lot.
        ///		   
        ///When an apartment building is in use (occupied),
        ///the LotAdjuster cannot modify the lot.
        ///	.
        /// </summary>
        internal static string MessageOccupiedApartment {
            get {
                return ResourceManager.GetString("MessageOccupiedApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road is no longer at a relative elevation of 0.
        ///This can cause unexpected game behavior.
        ///
        ///Do you want to continue?
        ///	.
        /// </summary>
        internal static string MessageRoadElevation {
            get {
                return ResourceManager.GetString("MessageRoadElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LotAdjuster was not able to remove enough terrain paints.
        ///There are still too many terrain paints on your lot..
        /// </summary>
        internal static string MessageStillTooManyTerrainPaints {
            get {
                return ResourceManager.GetString("MessageStillTooManyTerrainPaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many terrain paints on your lot.
        ///Would you like to have unused terrain paints removed?.
        /// </summary>
        internal static string MessageTooManyTerrainPaints {
            get {
                return ResourceManager.GetString("MessageTooManyTerrainPaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version: {0}.
        ///	
        ///The LotAdjuster only supports Expansion and Stuff Packs
        ///up to and including {1}.
        ///
        ///Do you want to continue?
        ///	.
        /// </summary>
        internal static string MessageWrongVer {
            get {
                return ResourceManager.GetString("MessageWrongVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Neighbourhood:.
        /// </summary>
        internal static string NBTitle {
            get {
                return ResourceManager.GetString("NBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There are no lots available in the currently selected neighborhood.
        ///
        ///Click Back to select another neighborhood.
        ///.
        /// </summary>
        internal static string NoLot {
            get {
                return ResourceManager.GetString("NoLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Lots Available.
        /// </summary>
        internal static string NoLotTitle {
            get {
                return ResourceManager.GetString("NoLotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Neighborhoods Available.
        /// </summary>
        internal static string NoNBTitle {
            get {
                return ResourceManager.GetString("NoNBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There are no neighborhoods available in the standard Sims 2 location.
        ///
        ///Click Browse... to select a neighborhood.
        ///.
        /// </summary>
        internal static string NoNeighborhood {
            get {
                return ResourceManager.GetString("NoNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount to enlarge or shrink the lot, viewed from the front.
        ///	.
        /// </summary>
        internal static string ShrinkExpl {
            get {
                return ResourceManager.GetString("ShrinkExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!  Unsupported Version..
        /// </summary>
        internal static string TitleCorruptLot {
            get {
                return ResourceManager.GetString("TitleCorruptLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string TitleKeepStreet {
            get {
                return ResourceManager.GetString("TitleKeepStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string TitleMoveLot {
            get {
                return ResourceManager.GetString("TitleMoveLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value changed.
        /// </summary>
        internal static string TitleNoChange {
            get {
                return ResourceManager.GetString("TitleNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!  Apartment Building is Occupied.
        /// </summary>
        internal static string TitleOccupiedApartment {
            get {
                return ResourceManager.GetString("TitleOccupiedApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        internal static string TitleRoadElevation {
            get {
                return ResourceManager.GetString("TitleRoadElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Terrain Paints.
        /// </summary>
        internal static string TitleTooManyTerrainPaints {
            get {
                return ResourceManager.GetString("TitleTooManyTerrainPaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!  Unsupported Version..
        /// </summary>
        internal static string TitleWrongVer {
            get {
                return ResourceManager.GetString("TitleWrongVer", resourceCulture);
            }
        }
    }
}
